### ISSUE TITLE
Enhancement: Adding an RF69 chip for added home automation functionality

### ISSUE THREAD

**Issue by darkmastermindz** [gcormier/megadesk#63] opened 2021-05-27 02:31 UTC
I would like to get some guidance to add Bluetooth using a RF69 chip to the board. 
I would be willing to make software to control with an app.

Thanks for the help and consideration.

**Comment by gcormier** [comment] 2021-05-27 18:26
This is mostly a duplicate of #11 

There just isn't enough space on the board to add a wireless chip. The best alternatives are the serial implementation with an external board of choice, such as a NodeMCU, etc. and to communicate over serial.

Also, we need to be mindful of the current draw. Right now the average draw is around 10mA, which keeps the heat dissipation for the linear regulators rather low. Increasing the demand could push the thermals too high.

Of course, an external case is always an option. At that point though we're outside the original scope of the project :) We would need 3D design, buttons, and users would need a 3D printer.

**Closed as completed** 2021-06-09 15:56 UTC
